#define             EMPIEZA         1
#define             END             2
#define             LEER            3
#define             ESCRIBIR        4
#define             ID              5
#define             A_PAREN         6
#define             C_PAREN         7
#define             SEMICOLON       8
#define             COMA            9
#define             ASIG_OP         10
#define             MAS_OP          11
#define             MENOS_OP        12
#define             A_LLAVE         13
#define             C_LLAVE         14
#define             VAR             15
#define             CONST           16
#define             SI              17
#define             SINO            18
#define             MIENTRAS        19
#define             POR_OP          20
#define             DIV_OP          21
#define		    NUM		    22
#define		    CADENA	    23
