CXX = g++
CXXFLAGS = -std=c++11 -Wall
LDFLAGS =

SRC_DIR = src
BUILD_DIR = build
BIN_DIR = bin

SRCS = $(wildcard $(SRC_DIR)/*.cpp)
OBJS = $(patsubst $(SRC_DIR)/%.cpp,$(BUILD_DIR)/%.obj,$(SRCS))
EXECUTABLE = $(BIN_DIR)/sbr.exe

all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJS)
	@mkdir -p $(BIN_DIR)
	$(CXX) $(LDFLAGS) $^ -o $@

$(BUILD_DIR)/%.obj: $(SRC_DIR)/%.cpp
	@mkdir -p $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) /c $< /Fo$@

clean:
	rmdir /s /q $(BUILD_DIR) $(BIN_DIR)

.PHONY: all clean
